### ISSUE TITLE
Adapter for Trino

### ISSUE THREAD

**Issue by Cabeda** [dbt-labs/dbt-presto#39]
With the rename of prestosql to Trino I think this adapter will stop to work for the ones not using PrestoDB (developed by facebook). 

Should a new one be created for the ones using Trino?

**Comment by victorcouste** [comment]
For info with the additional **protocol.v1.alternate-header-name=Presto** configuration property in Trino conf, dbt-presto plugin works well with last Trino version trino-server-355

**Comment by Cabeda** [comment]
@victorcouste that's great! However, as stated on [trino docs](https://trino.io/docs/current/admin/properties-general.html?highlight=alternate%20header#protocol-v1-alternate-header-name) I think we should consider this as a temporary solution

**Comment by victorcouste** [comment]
@Cabeda yes I think it should be a temporary solution, waiting dbt to accept "trino" as the header name

**Comment by findinpath** [comment]
I'm going to try locally to perform the string replacement (presto -> trino) and use the trino python client and see if creating this new adapter works without too much effort.
In case if it does and it gets polished enough, can this be taken under the fishanalytics umbrella?

**Comment by findinpath** [comment]
I have released in the meantime dbt-trino package to pypi .

See
https://github.com/findinpath/dbt-trino


I think that this issue can be closed now
