### ISSUE TITLE
Source freshness is not implemented in dbt-presto

### ISSUE THREAD

**Issue by wrborigin** [dbt-labs/dbt-presto#55]
Trying to use source_freshness feature with dbt-presto returns

```
Runtime Error in source test (models/schema.yml)
  ERROR: current_timestamp macro not implemented for adapter presto
```

but this is not documented anywhere.

**Comment by wrborigin** [comment]
I looked into implementing it, and the macro is straightforward enough

```
{% macro presto__current_timestamp() -%}
  localtimestamp
{%- endmacro %}
```

but now I'm getting this error:

    2021-07-13 10:22:19.077238 (MainThread):   Expected a timestamp value when querying field 'CAST(date AS TIMESTAMP)' of table "postgresql"."public"."test" but received value of type 'str' instead

and it seems that the problem is that [here](https://github.com/dbt-labs/dbt/blob/f460d275baa4df8cf8713f27e198a3577d6ea71c/core/dbt/adapters/base/impl.py#L96) dbt expects to get datetime value but Presto client library actually returns Python string.

So I'm not sure if this is fixable without touching dbt core and asking it to convert it to datetime there, instead.

**Comment by friendofasquid** [comment]
@wrborigin — Is `localtimestamp` correct, or should this be `CURRENT_TIMESTAMP`?

**Comment by wrborigin** [comment]
@friendofasquid Hmm you might be right. It's a bit more complicated.

Presto/Trino `current_timestamp` returns timestamp with timezone.

[Postgres adapter](https://github.com/dbt-labs/dbt/blob/develop/plugins/postgres/dbt/include/postgres/macros/adapters.sql#L121) uses `now()` which seems to be equivalent to `current_timestamp` except it's the time of transaction start but that doesn't matter here. https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-CURRENT 

[Redshift adapter](https://github.com/dbt-labs/dbt/blob/develop/plugins/redshift/dbt/include/redshift/macros/adapters.sql#L217) uses `getdate()` which seems to be alias 

[Snowflake](https://github.com/dbt-labs/dbt/blob/develop/plugins/snowflake/dbt/include/snowflake/macros/adapters.sql#L123) uses `current_timestamp` explicitly converted to UTC for some reason. I don't know if that conversion also makes it timestamp without timezone or if the timezone stays, just its UTC.

So I think I got confused by Snowflake conversion when looking for inspiration in the other adapters.

The other tricky part is that Presto with Hive, which I think is the most common use case, can't store timestamp with timezone because Hive doesn't support timestamp with timezone type. Meaning whatever timestamp you compare this with is likely going to be without timezone. That's why I'm used to use `localtimestamp` everywhere, because `current_timestamp` just doesn't work most of the time.

**Comment by friendofasquid** [comment]
I use Presto with Hive and have definitely gotten errors around Timestamp With time zone. However, this only happens we trying to persist data. I think it's a metastore error. 

For SELECT queries it should be fine. 

Does using 'CURRENT_TIMESTAMP' make the error go away?

**Comment by friendofasquid** [comment]
If snapshot freshness doesn't work on Presto, I'll probably be diving into this shortly as well. 

Another avenue is to have a look at what the author of dbt-athena has done.

**Comment by friendofasquid** [comment]
I tried using 

```
{% macro presto__current_timestamp() -%}
    cast(now() as timestamp)
{%- endmacro %}
```

which I stole from `dbt-athena`. This seems fine, but specifying the freshness column on my sources gives that error. Here's an attempt using the same approach, but on the sources side.

```
Database Error in source product_feedback (models/sources__saas.yml)
  Expected a timestamp value when querying field 'CAST(NOW() AS TIMESTAMP)' of table "restricted"."incoming_appflow_salesforce"."Product_Feedback__c" but received value of type 'str' instead
```

**Comment by jtcohen6** [comment]
@wrborigin @friendofasquid I'd love to figure out a way to get this working for Presto/Trino. What's the string returned by `current_timestamp`/`cast(now() as timestamp)`? Is there a simple tweak we could make so that the returned value is recognized as a python `datetime`, [including `tzinfo`](https://github.com/dbt-labs/dbt/blob/f460d275baa4df8cf8713f27e198a3577d6ea71c/core/dbt/adapters/base/impl.py#L94)?

**Comment by friendofasquid** [comment]
@jtcohen6 I can't see an easy fix here. Seems like an issue with the underlying library.

**Comment by wrborigin** [comment]
Closing this sinde dbt-presto is abandonware.
