### ISSUE TITLE
Configurable http_headers and http_scheme in presto profile

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-presto#68]
We have a use case at Shopify for specifying custom http headers to our Presto cluster for routing queries to specific clusters. Additionally, supporting a configurable http_scheme would be useful in combination with http_headers - for example, using the `{'Authorization': <token>}` header in combination with `https` as the http_scheme.

It looks like this change would mostly be a matter of plumbing the configurations through to the [`prestodb.dbapi.connect` call in connections.py](https://github.com/dbt-labs/dbt-presto/blob/master/dbt/adapters/presto/connections.py#L167-L176).

**Comment by MichelleArk** [comment]
I have a fix drafted up for this but will need write access to to the repo. @jtcohen6 is this something you can help me out with? :)

**Comment by jtcohen6** [comment]
@MichelleArk Absolutely! I'd very much welcome the contribution :)

Would it be possible for you to fork this repo, into either your org's or your personal GitHub account, and then open a PR from the fork? That's the simplest way to review + merge PRs from external contributors. If that's not something you're able to do, I can look into other options.

**Comment by MichelleArk** [comment]
@jtcohen6 - Done! https://github.com/dbt-labs/dbt-presto/pull/69
